[project]
name = "travel-ai-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.17.0",
    "pydantic>=2.12.2",
    "python-dotenv>=1.1.1",
]
